function result = calculateMetrics(waiting,...
                                   finish,...
                                   busyTime,...
                                   priority,...
                                   arrival,...
                                   service,...
                                   simulationTime,...
                                   numDoctors)

result.avgWaiting = mean(waiting);

result.avgQueue = ...
    sum(waiting>0)/length(waiting);

result.totalServed = ...
    sum(finish<=simulationTime);

result.utilization = ...
    sum(busyTime)/(numDoctors*simulationTime);

result.waiting = waiting;
result.finish = finish;
result.priority = priority;
result.arrival = arrival;
result.service = service;

result.criticalWaiting = ...
    mean(waiting(priority==1));

result.urgentWaiting = ...
    mean(waiting(priority==2));

result.normalWaiting = ...
    mean(waiting(priority==3));

end