function result = calculateMetrics(waiting,...
                                   busyTime,...
                                   finish,...
                                   simulationTime,...
                                   numDoctors)

result.avgWaiting = mean(waiting);

result.totalServed = ...
    sum(finish<=simulationTime);

result.utilization = ...
sum(busyTime)/(numDoctors*simulationTime);

result.avgQueue = ...
    sum(waiting>0)/length(waiting);

end