function [AverageWaitingTime,...
          AverageSystemTime,...
          ProbabilityWait,...
          Makespan,...
          OverallUtilization] = ...
RunCompareSimulation( ...
N,...
peakchoice,...
numGenChoice,...
numDoctors)

% 暂时用假数据测试 Compare Module

AverageWaitingTime = rand()*20;
AverageSystemTime = rand()*30;
ProbabilityWait = rand()*100;
Makespan = rand()*200;
OverallUtilization = rand()*100;

end